<MainScreen>:
    name: 'main'
    FloatLayout:
        size_hint: None, None


        Label:
            text: 'Welcome to TripMe'
            font_size: 20
            size: 60, 60
            x: root.width * .4
            y:root.height * .7

        Button:
            id: get_started
            text: "Get Started"
            size: 400, 100
            x: root.width * 0.45
            y:root.height * 0.3
            color: 0, 1, 0, 1
            on_press: root.getStarted()




